using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
namespace EduFlow.Api;

[ApiController, Route("api/auth")]
public class AuthController(EduFlowDbContext db, ITokenService tokens) : ControllerBase
{
    [HttpPost("register")] public async Task<IActionResult> Register(RegisterRequest r) { if (await db.Users.AnyAsync(x => x.Email == r.Email.ToLower())) return Conflict(new { message = "Пользователь с таким e-mail уже существует." }); var u = new User { FirstName = r.FirstName, LastName = r.LastName, Email = r.Email.ToLower(), PasswordHash = BCrypt.Net.BCrypt.HashPassword(r.Password) }; db.Users.Add(u); await db.SaveChangesAsync(); return Created("", new { token = tokens.Create(u), user = View(u) }); }
    [HttpPost("login")] public async Task<IActionResult> Login(LoginRequest r) { var u = await db.Users.SingleOrDefaultAsync(x => x.Email == r.Email.ToLower()); if (u is null || !BCrypt.Net.BCrypt.Verify(r.Password, u.PasswordHash)) return Unauthorized(new { message = "Неверный e-mail или пароль." }); if (u.IsBlocked) return StatusCode(403, new { message = "Учётная запись заблокирована." }); return Ok(new { token = tokens.Create(u), user = View(u) }); }
    [Authorize, HttpGet("me")] public async Task<IActionResult> Me() { var u = await db.Users.FindAsync(Id()); return Ok(View(u!)); }
    [Authorize, HttpPut("me")] public async Task<IActionResult> Update(ProfileRequest r) { var u = await db.Users.FindAsync(Id()); u!.FirstName = r.FirstName; u.LastName = r.LastName; u.AvatarUrl = r.AvatarUrl; u.Bio = r.Bio; u.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(); return Ok(View(u)); }
    [Authorize, HttpPut("change-password")] public async Task<IActionResult> ChangePassword(ChangePasswordRequest r) { var u = await db.Users.FindAsync(Id()); if (u is null || !BCrypt.Net.BCrypt.Verify(r.CurrentPassword, u.PasswordHash)) return BadRequest(new { message = "Текущий пароль указан неверно." }); u.PasswordHash = BCrypt.Net.BCrypt.HashPassword(r.NewPassword); u.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(); return NoContent(); }
    Guid Id() => Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!); public static object View(User u) => new { id = u.Id, firstName = u.FirstName, lastName = u.LastName, email = u.Email, role = u.Role.ToString(), isBlocked = u.IsBlocked, avatarUrl = u.AvatarUrl, bio = u.Bio };
}

[ApiController, Route("api")]
public class EduController(EduFlowDbContext db) : ControllerBase
{
    Guid UserId() => Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!); bool Is(params UserRole[] r) => r.Contains(Enum.Parse<UserRole>(User.FindFirstValue(ClaimTypes.Role)!)); void Log(string action, string details) => db.ActivityLogs.Add(new ActivityLog { ActorId = UserId(), Action = action, Details = details }); async Task<bool> HasActiveCourse(Guid studentId) => await db.Enrollments.Where(e => e.StudentId == studentId).AnyAsync(e => !e.Course!.Assignments.Any() || e.Course.Assignments.Any(a => !a.Submissions.Any(s => s.StudentId == studentId && s.Score.HasValue)));
    [HttpGet("categories")] public async Task<IActionResult> Categories() => Ok(await db.Categories.OrderBy(x => x.Name).ToListAsync());
    [Authorize(Roles = "Administrator"), HttpPost("categories")] public async Task<IActionResult> AddCategory(Category c) { db.Categories.Add(c); await db.SaveChangesAsync(); return Created("", c); }
    [HttpGet("courses")] public async Task<IActionResult> Courses([FromQuery] string? search, [FromQuery] int? categoryId, [FromQuery] int page = 1, [FromQuery] int pageSize = 12) { var q = db.Courses.Include(c => c.Category).Include(c => c.Teacher).Include(c => c.Enrollments).AsQueryable(); if (!string.IsNullOrWhiteSpace(search)) q = q.Where(c => c.Title.ToLower().Contains(search.ToLower())); if (categoryId.HasValue) q = q.Where(c => c.CategoryId == categoryId); var total = await q.CountAsync(); var data = await q.OrderByDescending(c => c.CreatedAt).Skip((page - 1) * pageSize).Take(pageSize).Select(c => new { c.Id, c.Title, c.Description, c.CoverUrl, category = c.Category!.Name, teacher = c.Teacher == null ? null : c.Teacher.FirstName + " " + c.Teacher.LastName, students = c.Enrollments.Count }).ToListAsync(); return Ok(new { items = data, total, page, pageSize }); }
    [HttpGet("courses/{id:int}")] public async Task<IActionResult> Course(int id) { var c = await db.Courses.Include(x => x.Category).Include(x => x.Teacher).Include(x => x.Modules).ThenInclude(x => x.Materials).Include(x => x.Assignments).Include(x => x.Announcements).Include(x => x.Enrollments).SingleOrDefaultAsync(x => x.Id == id); if (c == null) return NotFound(new { message = "Курс не найден." }); return Ok(new { id = c.Id, title = c.Title, description = c.Description, coverUrl = c.CoverUrl, category = new { id = c.Category!.Id, name = c.Category.Name }, teacher = c.Teacher == null ? null : new { id = c.Teacher.Id, firstName = c.Teacher.FirstName, lastName = c.Teacher.LastName }, students = c.Enrollments.Count, modules = c.Modules.OrderBy(x => x.Position).Select(x => new { id = x.Id, title = x.Title, description = x.Description, position = x.Position, materials = x.Materials.Select(m => new { id = m.Id, title = m.Title, description = m.Description, url = m.Url, type = m.Type.ToString() }) }), assignments = c.Assignments.OrderBy(x => x.DueDate).Select(a => new { id = a.Id, title = a.Title, description = a.Description, dueDate = a.DueDate, maxScore = a.MaxScore, moduleId = a.ModuleId, module = a.Module == null ? null : a.Module.Title, attachmentUrl = a.AttachmentUrl, attachmentName = a.AttachmentName }), announcements = c.Announcements.OrderByDescending(a => a.CreatedAt).Select(a => new { id = a.Id, title = a.Title, content = a.Content, createdAt = a.CreatedAt }) }); }
    [Authorize(Roles = "Administrator,Teacher"), HttpPost("courses")] public async Task<IActionResult> CreateCourse(CourseRequest r) { if (Is(UserRole.Teacher)) r = r with { TeacherId = UserId() }; var c = new Course { Title = r.Title, Description = r.Description, CategoryId = r.CategoryId, TeacherId = r.TeacherId, CoverUrl = r.CoverUrl }; db.Courses.Add(c); await db.SaveChangesAsync(); return Created($"api/courses/{c.Id}", c); }
    [Authorize(Roles = "Administrator"), HttpPut("admin/courses/{id:int}/teacher/{teacherId:guid}")] public async Task<IActionResult> AssignTeacher(int id, Guid teacherId) { var c = await db.Courses.FindAsync(id); var teacher = await db.Users.FindAsync(teacherId); if (c == null || teacher == null || teacher.Role != UserRole.Teacher) return BadRequest(new { message = "Курс или преподаватель не найден." }); c.TeacherId = teacherId; c.UpdatedAt = DateTime.UtcNow; Log("Назначен преподаватель", $"{teacher.FirstName} {teacher.LastName} закреплён за курсом «{c.Title}»"); await db.SaveChangesAsync(); return NoContent(); }
    [Authorize(Roles = "Administrator,Teacher"), HttpDelete("courses/{id:int}")] public async Task<IActionResult> DeleteCourse(int id) { var c = await db.Courses.FindAsync(id); if (c == null) return NotFound(); if (Is(UserRole.Teacher) && c.TeacherId != UserId()) return Forbid(); db.Courses.Remove(c); await db.SaveChangesAsync(); return NoContent(); }
    [Authorize(Roles = "Student"), HttpPost("courses/{id:int}/enroll")] public async Task<IActionResult> Enroll(int id) { if (!await db.Courses.AnyAsync(x => x.Id == id)) return NotFound(); if (await db.Enrollments.AnyAsync(x => x.CourseId == id && x.StudentId == UserId())) return Conflict(new { message = "Вы уже записаны на этот курс." }); if (await HasActiveCourse(UserId())) return Conflict(new { message = "Сначала завершите текущий курс: все задания должны быть проверены преподавателем." }); db.Enrollments.Add(new Enrollment { CourseId = id, StudentId = UserId() }); await db.SaveChangesAsync(); return NoContent(); }
    [Authorize, HttpGet("my-courses")] public async Task<IActionResult> MyCourses() { var id = UserId(); if (Is(UserRole.Teacher)) return Ok(await db.Courses.Where(c => c.TeacherId == id).OrderBy(c => c.Title).Select(c => new { id = c.Id, title = c.Title, description = c.Description, category = c.Category == null ? null : new { id = c.Category.Id, name = c.Category.Name }, modules = c.Modules.OrderBy(m => m.Position).Select(m => new { id = m.Id, title = m.Title, description = m.Description, position = m.Position }), students = c.Enrollments.OrderBy(e => e.Student!.LastName).Select(e => new { id = e.StudentId, name = e.Student!.FirstName + " " + e.Student.LastName, email = e.Student.Email }) }).ToListAsync()); return Ok(await db.Enrollments.Where(e => e.StudentId == id).Include(e => e.Course).ThenInclude(c => c!.Category).Select(e => e.Course).ToListAsync()); }
    [Authorize(Roles = "Administrator,Teacher"), HttpPost("courses/{courseId:int}/assignments")] public async Task<IActionResult> AddAssignment(int courseId, AssignmentRequest r) { if (Is(UserRole.Teacher) && !await db.Courses.AnyAsync(c => c.Id == courseId && c.TeacherId == UserId())) return Forbid(); if (!await db.Modules.AnyAsync(m => m.Id == r.ModuleId && m.CourseId == courseId)) return BadRequest(new { message = "Выберите урок из программы этого курса." }); var a = new Assignment { CourseId = courseId, ModuleId = r.ModuleId, Title = r.Title, Description = r.Description, DueDate = DateTime.UtcNow.AddDays(r.DaysToComplete), MaxScore = 10, AttachmentUrl = r.AttachmentUrl, AttachmentName = r.AttachmentName }; db.Assignments.Add(a); Log("Опубликовано домашнее задание", $"Задание «{a.Title}» опубликовано для курса №{courseId}"); await db.SaveChangesAsync(); return Created("", a); }
    [Authorize(Roles = "Teacher"), HttpGet("teacher/assignments")] public async Task<IActionResult> TeacherAssignments() { var id = UserId(); return Ok(await db.Assignments.Where(a => a.Course!.TeacherId == id).OrderBy(a => a.DueDate).Select(a => new { id = a.Id, title = a.Title, description = a.Description, dueDate = a.DueDate, maxScore = a.MaxScore, courseId = a.CourseId, course = a.Course!.Title, module = a.Module == null ? null : a.Module.Title, attachmentUrl = a.AttachmentUrl, attachmentName = a.AttachmentName, submitted = a.Submissions.Count() }).ToListAsync()); }
    [Authorize(Roles = "Teacher"), HttpDelete("assignments/{id:int}")] public async Task<IActionResult> RevokeAssignment(int id) { var a = await db.Assignments.Include(x => x.Course).Include(x => x.Submissions).SingleOrDefaultAsync(x => x.Id == id); if (a == null) return NotFound(); if (a.Course!.TeacherId != UserId()) return Forbid(); db.Submissions.RemoveRange(a.Submissions); db.Assignments.Remove(a); await db.SaveChangesAsync(); return NoContent(); }
    [Authorize(Roles = "Administrator,Teacher"), HttpPost("courses/{courseId:int}/modules")] public async Task<IActionResult> AddModule(int courseId, ModuleRequest r) { var course = await db.Courses.FindAsync(courseId); if (course == null) return NotFound(new { message = "Курс не найден." }); if (Is(UserRole.Teacher) && course.TeacherId != UserId()) return Forbid(); var m = new Module { CourseId = courseId, Title = r.Title, Description = r.Description, Position = r.Position }; db.Modules.Add(m); await db.SaveChangesAsync(); return Created("", m); }
    [Authorize(Roles = "Administrator,Teacher"), HttpPost("modules/{moduleId:int}/materials")] public async Task<IActionResult> AddMaterial(int moduleId, MaterialRequest r) { var module = await db.Modules.Include(x => x.Course).SingleOrDefaultAsync(x => x.Id == moduleId); if (module == null) return NotFound(new { message = "Урок не найден." }); if (Is(UserRole.Teacher) && module.Course!.TeacherId != UserId()) return Forbid(); var m = new LearningMaterial { ModuleId = moduleId, Title = r.Title, Description = r.Description, Url = r.Url, Type = r.Type }; db.Materials.Add(m); await db.SaveChangesAsync(); return Created("", m); }
    [Authorize(Roles = "Teacher"), HttpPost("teacher/materials/upload")] public async Task<IActionResult> UploadMaterial(IFormFile file) { if (file == null || file.Length == 0) return BadRequest(new { message = "Выберите файл." }); if (file.Length > 15 * 1024 * 1024) return BadRequest(new { message = "Максимальный размер файла — 15 МБ." }); var ext = Path.GetExtension(file.FileName).ToLowerInvariant(); if (ext is not ".pdf" and not ".doc" and not ".docx") return BadRequest(new { message = "Можно загрузить только PDF, DOC или DOCX." }); var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", "materials"); Directory.CreateDirectory(folder); var stored = $"{Guid.NewGuid():N}{ext}"; await using (var stream = System.IO.File.Create(Path.Combine(folder, stored))) await file.CopyToAsync(stream); return Ok(new { url = $"{Request.Scheme}://{Request.Host}/uploads/materials/{stored}", fileName = file.FileName, type = MaterialType.Document.ToString() }); }
    [Authorize(Roles = "Teacher"), HttpPost("teacher/materials")] public async Task<IActionResult> CreateTeacherMaterial(TeacherMaterialRequest r) { var course = await db.Courses.Include(c => c.Modules).SingleOrDefaultAsync(c => c.Id == r.CourseId && c.TeacherId == UserId()); if (course == null) return Forbid(); var module = course.Modules.FirstOrDefault(m => m.Id == r.ModuleId); if (module == null) return BadRequest(new { message = "Сначала выберите урок из программы курса." }); db.Materials.Add(new LearningMaterial { ModuleId = module.Id, Title = r.Title, Description = r.Description, Url = r.Url, Type = r.Type }); await db.SaveChangesAsync(); return Created("", new { message = "Материал опубликован." }); }
    [Authorize(Roles = "Teacher"), HttpGet("teacher/materials")] public async Task<IActionResult> TeacherMaterials() { var id = UserId(); return Ok(await db.Courses.Where(c => c.TeacherId == id).Select(c => new { id = c.Id, title = c.Title, modules = c.Modules.OrderBy(m => m.Position).Select(m => new { id = m.Id, title = m.Title, description = m.Description, materials = m.Materials.Select(x => new { id = x.Id, title = x.Title, description = x.Description, url = x.Url, type = x.Type.ToString() }) }) }).ToListAsync()); }
    [Authorize(Roles = "Teacher"), HttpPost("teacher/courses/{courseId:int}/program-modules")] public async Task<IActionResult> AddProgramModule(int courseId, ModuleRequest r) { var course = await db.Courses.Include(c => c.Modules).SingleOrDefaultAsync(c => c.Id == courseId && c.TeacherId == UserId()); if (course == null) return Forbid(); if (course.Modules.Count >= 12) return BadRequest(new { message = "В программе может быть не более 12 уроков." }); if (course.Modules.Any(m => m.Title.ToLower() == r.Title.Trim().ToLower())) return Conflict(new { message = "Урок с таким названием уже есть." }); db.Modules.Add(new Module { CourseId = courseId, Title = r.Title.Trim(), Description = r.Description, Position = course.Modules.Count + 1 }); await db.SaveChangesAsync(); return Created("", new { message = "Урок добавлен в программу." }); }
    [Authorize(Roles = "Teacher"), HttpDelete("teacher/modules/{id:int}")] public async Task<IActionResult> DeleteProgramModule(int id) { var module = await db.Modules.Include(m => m.Course).Include(m => m.Materials).Include(m => m.Assignments).ThenInclude(a => a.Submissions).SingleOrDefaultAsync(m => m.Id == id); if (module == null) return NotFound(); if (module.Course!.TeacherId != UserId()) return Forbid(); db.Submissions.RemoveRange(module.Assignments.SelectMany(a => a.Submissions)); db.Assignments.RemoveRange(module.Assignments); db.Materials.RemoveRange(module.Materials); db.Modules.Remove(module); await db.SaveChangesAsync(); return NoContent(); }
    [Authorize(Roles = "Teacher"), HttpGet("teacher/course-program")] public async Task<IActionResult> TeacherProgram() { var id = UserId(); return Ok(await db.Courses.Where(c => c.TeacherId == id).Select(c => new { id = c.Id, title = c.Title, description = c.Description, modules = c.Modules.OrderBy(m => m.Position).Select(m => new { id = m.Id, title = m.Title, description = m.Description, position = m.Position, materials = m.Materials.Count }) }).ToListAsync()); }
    [Authorize(Roles = "Student"), HttpDelete("courses/{id:int}/enroll")] public async Task<IActionResult> Leave(int id) { var e = await db.Enrollments.SingleOrDefaultAsync(x => x.CourseId == id && x.StudentId == UserId()); if (e == null) return NotFound(); if (await db.Submissions.Include(x => x.Assignment).AnyAsync(x => x.StudentId == UserId() && x.Assignment!.CourseId == id)) return BadRequest(new { message = "Нельзя покинуть курс: уже есть сданные работы." }); db.Enrollments.Remove(e); await db.SaveChangesAsync(); return NoContent(); }
    [Authorize(Roles = "Student"), HttpGet("courses/{id:int}/progress")] public async Task<IActionResult> Progress(int id) { var total = await db.Assignments.CountAsync(x => x.CourseId == id); var subs = await db.Submissions.Include(x => x.Assignment).Where(x => x.StudentId == UserId() && x.Assignment!.CourseId == id).ToListAsync(); return Ok(new { total, completed = subs.Count, percent = total == 0 ? 0 : Math.Round(subs.Count * 100d / total), average = subs.Where(x => x.Score.HasValue).Select(x => (double)x.Score!.Value).DefaultIfEmpty().Average() }); }
    [Authorize(Roles = "Student"), HttpPost("assignments/{id:int}/submission/upload")] public async Task<IActionResult> UploadSubmissionFile(int id, IFormFile file) { if (!await db.Assignments.AnyAsync(a => a.Id == id && db.Enrollments.Any(e => e.CourseId == a.CourseId && e.StudentId == UserId()))) return Forbid(); if (file == null || file.Length == 0) return BadRequest(new { message = "Выберите файл." }); if (file.Length > 15 * 1024 * 1024) return BadRequest(new { message = "Максимальный размер файла — 15 МБ." }); var ext = Path.GetExtension(file.FileName).ToLowerInvariant(); if (ext is not ".pdf" and not ".doc" and not ".docx") return BadRequest(new { message = "Можно загрузить только PDF, DOC или DOCX." }); var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", "submissions"); Directory.CreateDirectory(folder); var stored = $"{Guid.NewGuid():N}{ext}"; await using (var stream = System.IO.File.Create(Path.Combine(folder, stored))) await file.CopyToAsync(stream); return Ok(new { url = $"{Request.Scheme}://{Request.Host}/uploads/submissions/{stored}", fileName = file.FileName }); }
    [Authorize(Roles = "Student"), HttpPost("assignments/{id:int}/submission")] public async Task<IActionResult> Submit(int id, SubmissionRequest r) { var s = await db.Submissions.SingleOrDefaultAsync(x => x.AssignmentId == id && x.StudentId == UserId()); if (s == null) { s = new Submission { AssignmentId = id, StudentId = UserId() }; db.Submissions.Add(s); } s.TextAnswer = r.TextAnswer; s.FileUrl = r.FileUrl; s.SubmittedAt = DateTime.UtcNow; s.NeedsRevision = false; Log("Работа отправлена на проверку", $"Студент отправил работу по заданию №{id}"); await db.SaveChangesAsync(); return Ok(s); }
    [Authorize(Roles = "Administrator,Teacher"), HttpGet("assignments/{id:int}/submissions")] public async Task<IActionResult> Submissions(int id) { var assignment = await db.Assignments.Include(x => x.Course).SingleOrDefaultAsync(x => x.Id == id); if (assignment == null) return NotFound(new { message = "Задание не найдено." }); if (Is(UserRole.Teacher) && assignment.Course!.TeacherId != UserId()) return Forbid(); return Ok(await db.Submissions.Where(s => s.AssignmentId == id).Include(s => s.Student).ToListAsync()); }
    [Authorize(Roles = "Administrator,Teacher"), HttpPut("submissions/{id:int}/grade")] public async Task<IActionResult> Grade(int id, GradeRequest r) { if (r.Score is < 1 or > 10 || string.IsNullOrWhiteSpace(r.Comment)) return BadRequest(new { message = "Укажите оценку от 1 до 10 и комментарий студенту." }); var s = await db.Submissions.Include(x => x.Assignment).Include(x => x.Student).SingleOrDefaultAsync(x => x.Id == id); if (s == null) return NotFound(new { message = "Работа не найдена." }); if (Is(UserRole.Teacher) && !await db.Courses.AnyAsync(c => c.Id == s.Assignment!.CourseId && c.TeacherId == UserId())) return Forbid(); s.Score = r.Score; s.NeedsRevision = false; s.TeacherComment = r.Comment.Trim(); Log("Поставлена оценка", $"{s.Student!.FirstName} {s.Student.LastName}: «{s.Assignment!.Title}» — {r.Score}/10"); await db.SaveChangesAsync(); return Ok(new { id = s.Id, score = s.Score, comment = s.TeacherComment }); }
    [Authorize(Roles = "Teacher"), HttpPut("submissions/{id:int}/return")] public async Task<IActionResult> ReturnForRevision(int id, ReturnSubmissionRequest r) { if (string.IsNullOrWhiteSpace(r.Comment)) return BadRequest(new { message = "Добавьте комментарий для студента." }); var s = await db.Submissions.Include(x => x.Assignment).Include(x => x.Student).SingleOrDefaultAsync(x => x.Id == id); if (s == null) return NotFound(new { message = "Работа не найдена." }); if (!await db.Courses.AnyAsync(c => c.Id == s.Assignment!.CourseId && c.TeacherId == UserId())) return Forbid(); s.Score = null; s.NeedsRevision = true; s.TeacherComment = r.Comment.Trim(); Log("Работа возвращена на доработку", $"{s.Student!.FirstName} {s.Student.LastName}: «{s.Assignment!.Title}»"); await db.SaveChangesAsync(); return Ok(new { id = s.Id, needsRevision = s.NeedsRevision, comment = s.TeacherComment }); }
    [Authorize(Roles = "Administrator,Teacher"), HttpPost("courses/{id:int}/announcements")] public async Task<IActionResult> Announce(int id, AnnouncementRequest r) { var course = await db.Courses.FindAsync(id); if (course == null) return NotFound(new { message = "Курс не найден." }); if (Is(UserRole.Teacher) && course.TeacherId != UserId()) return Forbid(); var a = new Announcement { CourseId = id, Title = r.Title, Content = r.Content }; db.Announcements.Add(a); await db.SaveChangesAsync(); return Created("", a); }
    [Authorize(Roles = "Administrator"), HttpGet("admin/users")] public async Task<IActionResult> Users([FromQuery] string? search, [FromQuery] UserRole? role) { var q = db.Users.AsQueryable(); if (search != null) q = q.Where(x => (x.FirstName + " " + x.LastName + x.Email).ToLower().Contains(search.ToLower())); if (role.HasValue) q = q.Where(x => x.Role == role); return Ok(await q.OrderBy(x => x.LastName).Select(x => AuthController.View(x)).ToListAsync()); }
    [Authorize(Roles = "Administrator"), HttpPut("admin/users/{id:guid}/block")] public async Task<IActionResult> Block(Guid id) { if (id == UserId()) return BadRequest(new { message = "Нельзя заблокировать собственную учётную запись." }); var u = await db.Users.FindAsync(id); if (u == null) return NotFound(); u.IsBlocked = !u.IsBlocked; await db.SaveChangesAsync(); return Ok(AuthController.View(u)); }
    [Authorize(Roles = "Administrator"), HttpPut("admin/users/{id:guid}/role")] public async Task<IActionResult> Role(Guid id, [FromBody] UserRole role) { var u = await db.Users.FindAsync(id); if (u == null) return NotFound(); u.Role = role; await db.SaveChangesAsync(); return Ok(AuthController.View(u)); }
    [Authorize(Roles = "Administrator"), HttpPut("admin/users/{id:guid}/password")] public async Task<IActionResult> ResetPassword(Guid id, ResetPasswordRequest r) { var u = await db.Users.FindAsync(id); if (u == null) return NotFound(); u.PasswordHash = BCrypt.Net.BCrypt.HashPassword(r.NewPassword); u.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(); return NoContent(); }
    [Authorize(Roles = "Administrator"), HttpPost("admin/enrollments")] public async Task<IActionResult> AdminEnroll(EnrollmentRequest r) { var student = await db.Users.FindAsync(r.StudentId); var course = await db.Courses.FindAsync(r.CourseId); if (student == null || student.Role != UserRole.Student || course == null) return BadRequest(new { message = "Студент или курс не найден." }); if (await db.Enrollments.AnyAsync(x => x.StudentId == r.StudentId && x.CourseId == r.CourseId)) return Conflict(new { message = "Студент уже записан." }); if (await HasActiveCourse(r.StudentId)) return Conflict(new { message = "У студента уже есть незавершённый курс. Назначить следующий можно после проверки всех заданий." }); db.Enrollments.Add(new Enrollment { StudentId = r.StudentId, CourseId = r.CourseId }); Log("Студент записан на курс", $"{student.FirstName} {student.LastName} добавлен в «{course.Title}»"); await db.SaveChangesAsync(); return NoContent(); }
    [Authorize(Roles = "Administrator"), HttpGet("admin/courses-roster")] public async Task<IActionResult> Roster() => Ok(await db.Courses.Include(c => c.Teacher).Include(c => c.Enrollments).ThenInclude(e => e.Student).Include(c => c.Modules).ThenInclude(m => m.Materials).Include(c => c.Assignments).OrderBy(c => c.Title).Select(c => new { c.Id, c.Title, c.Description, teacher = c.Teacher == null ? null : new { id = c.Teacher.Id, name = c.Teacher.FirstName + " " + c.Teacher.LastName }, modules = c.Modules.Count, materials = c.Modules.SelectMany(m => m.Materials).Count(), assignments = c.Assignments.Count, students = c.Enrollments.Select(e => new { id = e.StudentId, name = e.Student!.FirstName + " " + e.Student.LastName, email = e.Student.Email }) }).ToListAsync());
    [Authorize(Roles = "Administrator"), HttpDelete("admin/enrollments/{courseId:int}/{studentId:guid}")] public async Task<IActionResult> RemoveEnrollment(int courseId, Guid studentId) { var e = await db.Enrollments.Include(x => x.Course).Include(x => x.Student).SingleOrDefaultAsync(x => x.CourseId == courseId && x.StudentId == studentId); if (e == null) return NotFound(); db.Enrollments.Remove(e); Log("Студент снят с курса", $"{e.Student!.FirstName} {e.Student.LastName} снят с «{e.Course!.Title}»"); await db.SaveChangesAsync(); return NoContent(); }
    [Authorize(Roles = "Administrator"), HttpPost("admin/teachers")] public async Task<IActionResult> CreateTeacher(CreateTeacherRequest r) { if (await db.Users.AnyAsync(x => x.Email == r.Email.ToLower())) return Conflict(new { message = "Пользователь с таким e-mail уже существует." }); var u = new User { FirstName = r.FirstName, LastName = r.LastName, Email = r.Email.ToLower(), Role = UserRole.Teacher, PasswordHash = BCrypt.Net.BCrypt.HashPassword(r.Password) }; db.Users.Add(u); await db.SaveChangesAsync(); return Created("", AuthController.View(u)); }
    [Authorize(Roles = "Teacher"), HttpGet("teacher/submissions")] public async Task<IActionResult> TeacherSubmissions() { var id = UserId(); return Ok(await db.Submissions.Include(s => s.Student).Include(s => s.Assignment).ThenInclude(a => a!.Course).Where(s => s.Assignment!.Course!.TeacherId == id).OrderBy(s => s.Score.HasValue).ThenByDescending(s => s.SubmittedAt).Select(s => new { id = s.Id, assignmentId = s.AssignmentId, assignment = s.Assignment!.Title, course = s.Assignment.Course!.Title, student = s.Student!.FirstName + " " + s.Student.LastName, s.SubmittedAt, s.Score, s.TeacherComment, s.NeedsRevision, textAnswer = s.TextAnswer, fileUrl = s.FileUrl, maxScore = s.Assignment.MaxScore }).ToListAsync()); }
    [Authorize(Roles = "Student"), HttpGet("student/materials")] public async Task<IActionResult> StudentMaterials() { var id = UserId(); var course = await db.Enrollments.Where(e => e.StudentId == id && (!e.Course!.Assignments.Any() || e.Course.Assignments.Any(a => !a.Submissions.Any(s => s.StudentId == id && s.Score.HasValue)))).OrderByDescending(e => e.EnrolledAt).Select(e => new { id = e.CourseId, title = e.Course!.Title, description = e.Course.Description, teacher = e.Course.Teacher == null ? null : e.Course.Teacher.FirstName + " " + e.Course.Teacher.LastName, modules = e.Course.Modules.OrderBy(m => m.Position).Select(m => new { id = m.Id, title = m.Title, description = m.Description, materials = m.Materials.Select(x => new { id = x.Id, title = x.Title, description = x.Description, url = x.Url, type = x.Type.ToString() }) }) }).FirstOrDefaultAsync(); return Ok(course); }
    [Authorize(Roles = "Student"), HttpGet("student/course-program")] public async Task<IActionResult> StudentProgram() { var id = UserId(); var course = await db.Enrollments.Where(e => e.StudentId == id && (!e.Course!.Assignments.Any() || e.Course.Assignments.Any(a => !a.Submissions.Any(s => s.StudentId == id && s.Score.HasValue)))).OrderByDescending(e => e.EnrolledAt).Select(e => new { id = e.CourseId, title = e.Course!.Title, description = e.Course.Description, teacher = e.Course.Teacher == null ? null : e.Course.Teacher.FirstName + " " + e.Course.Teacher.LastName, modules = e.Course.Modules.OrderBy(m => m.Position).Select(m => new { id = m.Id, title = m.Title, description = m.Description, position = m.Position, materials = m.Materials.Count }) }).FirstOrDefaultAsync(); return Ok(course); }
    [Authorize(Roles = "Student"), HttpGet("student/dashboard")] public async Task<IActionResult> StudentDashboard() { var id = UserId(); var courses = await db.Enrollments.Where(e => e.StudentId == id && (!e.Course!.Assignments.Any() || e.Course.Assignments.Any(a => !a.Submissions.Any(s => s.StudentId == id && s.Score.HasValue)))).Include(e => e.Course).ThenInclude(c => c!.Assignments).Include(e => e.Course).ThenInclude(c => c!.Modules).ThenInclude(m => m.Materials).Select(e => new { id = e.CourseId, title = e.Course!.Title, description = e.Course.Description, teacher = e.Course.Teacher == null ? null : e.Course.Teacher.FirstName + " " + e.Course.Teacher.LastName, materials = e.Course.Modules.SelectMany(m => m.Materials).Count(), completed = e.Course.Assignments.Count(a => a.Submissions.Any(s => s.StudentId == id && s.Score.HasValue)), assignments = e.Course.Assignments.Select(a => new { id = a.Id, title = a.Title, dueDate = a.DueDate, maxScore = a.MaxScore, module = a.Module == null ? null : a.Module.Title, attachmentUrl = a.AttachmentUrl, attachmentName = a.AttachmentName, submission = a.Submissions.Where(s => s.StudentId == id).Select(s => new { s.Score, s.TeacherComment, s.SubmittedAt, s.FileUrl, s.NeedsRevision }).FirstOrDefault() }) }).ToListAsync(); return Ok(courses); }
    [Authorize(Roles = "Administrator"), HttpGet("admin/activity")] public async Task<IActionResult> Activity() { var logs = await db.ActivityLogs.OrderByDescending(x => x.CreatedAt).Take(20).ToListAsync(); var ids = logs.Where(x => x.ActorId.HasValue).Select(x => x.ActorId!.Value).Distinct().ToList(); var actors = await db.Users.Where(x => ids.Contains(x.Id)).ToDictionaryAsync(x => x.Id, x => x.FirstName + " " + x.LastName); return Ok(logs.Select(x => new { id = x.Id, action = x.Action, details = x.Details, createdAt = x.CreatedAt, actor = x.ActorId.HasValue && actors.ContainsKey(x.ActorId.Value) ? actors[x.ActorId.Value] : "Система" })); }
    [Authorize(Roles = "Administrator"), HttpGet("admin/statistics")] public async Task<IActionResult> Stats() => Ok(new { users = await db.Users.CountAsync(), students = await db.Users.CountAsync(x => x.Role == UserRole.Student), teachers = await db.Users.CountAsync(x => x.Role == UserRole.Teacher), courses = await db.Courses.CountAsync(), assignments = await db.Assignments.CountAsync(), submissions = await db.Submissions.CountAsync() });
}
