using System.ComponentModel.DataAnnotations;
namespace EduFlow.Api;

public enum UserRole { Administrator, Teacher, Student }
public enum MaterialType { Link, Video, Document }
public class User { public Guid Id { get; set; } = Guid.NewGuid(); [MaxLength(80)] public string FirstName { get; set; } = ""; [MaxLength(80)] public string LastName { get; set; } = ""; [EmailAddress] public string Email { get; set; } = ""; public string PasswordHash { get; set; } = ""; public UserRole Role { get; set; } = UserRole.Student; public bool IsBlocked { get; set; } public string? AvatarUrl { get; set; } public string? Bio { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; public List<Course> TeachingCourses { get; set; } = []; public List<Enrollment> Enrollments { get; set; } = []; public List<Submission> Submissions { get; set; } = []; }
public class Category { public int Id { get; set; } public string Name { get; set; } = ""; public string? Color { get; set; } public List<Course> Courses { get; set; } = []; }
public class Course { public int Id { get; set; } public string Title { get; set; } = ""; public string Description { get; set; } = ""; public string? CoverUrl { get; set; } public int CategoryId { get; set; } public Category? Category { get; set; } public Guid? TeacherId { get; set; } public User? Teacher { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; public List<Enrollment> Enrollments { get; set; } = []; public List<Module> Modules { get; set; } = []; public List<Assignment> Assignments { get; set; } = []; public List<Announcement> Announcements { get; set; } = []; }
public class Enrollment { public int Id { get; set; } public int CourseId { get; set; } public Course? Course { get; set; } public Guid StudentId { get; set; } public User? Student { get; set; } public DateTime EnrolledAt { get; set; } = DateTime.UtcNow; }
public class Module { public int Id { get; set; } public string Title { get; set; } = ""; public string? Description { get; set; } public int Position { get; set; } public int CourseId { get; set; } public Course? Course { get; set; } public List<LearningMaterial> Materials { get; set; } = []; public List<Assignment> Assignments { get; set; } = []; }
public class LearningMaterial { public int Id { get; set; } public string Title { get; set; } = ""; public string? Description { get; set; } public string Url { get; set; } = ""; public MaterialType Type { get; set; } public int ModuleId { get; set; } public Module? Module { get; set; } }
public class Assignment { public int Id { get; set; } public string Title { get; set; } = ""; public string Description { get; set; } = ""; public DateTime DueDate { get; set; } public int MaxScore { get; set; } = 10; public int CourseId { get; set; } public Course? Course { get; set; } public int? ModuleId { get; set; } public Module? Module { get; set; } public string? AttachmentUrl { get; set; } public string? AttachmentName { get; set; } public List<Submission> Submissions { get; set; } = []; }
public class Submission { public int Id { get; set; } public string TextAnswer { get; set; } = ""; public string? FileUrl { get; set; } public DateTime SubmittedAt { get; set; } = DateTime.UtcNow; public int? Score { get; set; } public string? TeacherComment { get; set; } public bool NeedsRevision { get; set; } public int AssignmentId { get; set; } public Assignment? Assignment { get; set; } public Guid StudentId { get; set; } public User? Student { get; set; } }
public class Announcement { public int Id { get; set; } public string Title { get; set; } = ""; public string Content { get; set; } = ""; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public int CourseId { get; set; } public Course? Course { get; set; } }
public class ActivityLog { public int Id { get; set; } public Guid? ActorId { get; set; } public string Action { get; set; } = ""; public string Details { get; set; } = ""; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
